### ISSUE TITLE
Timezone issues, proposing fix

### ISSUE THREAD

**Issue by groobo** [curzon01/mysql_SunRiseSet#1]
My local development server (MariaDB 8.0.27 on Mac OSX) does not understand UTC; when set time_zone='UTC' is run, it returns ERROR 1298 (HY000): Unknown or incorrect time zone: 'UTC'. While it could be fixed by running a script on the server, I would like to offer a solution where the function makes it more prone to issues like mine (replace UTC with +00:00): 
RETURN TIME(CONVERT_TZ(CONCAT(DATE(datex),' ',SEC_TO_TIME(UT * 3600.0)),'**+00:00**','SYSTEM'));

**Comment by curzon01** [comment]
Mariadb 8.0.27 doesn't exist, I think you're using MySQL 8.0.27

You need to fill your MySQL timezone tables, simply run

`mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql -p`
